name: fit_plan_proyecto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.8
  google_nav_bar: ^5.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  fluttertoast: ^8.2.8
  cloud_firestore: ^5.4.4
  google_sign_in: ^5.2.1 
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/ConsejosHidratacion/
    - assets/ConsejosNutricionales/
